backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Page Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Path", name: "title", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", default: ["appsolut"] }
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Teaser", name: "teaser", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "doc"
    label: "Documentation"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page Type", name: "type", widget: "select", default: "lesson", options: ["chapter", "lesson"]}
      - {label: "Chapter", name: "chapter", widget: "string"}
      - {label: "Position", name: "number", widget: "number", valueType: "int", min: 1, default: 1}
      - {label: "Path", name: "title", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "info"
    label: "Info"
    folder: "content/info"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Page Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Path", name: "title", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
